//! bundle — the chart-bundle pipeline as a LIBRARY module: S-101 portrayal asset
//! emission (colortables / linestyles / sprite / patterns / sprite-mln) built from
//! the embedded catalogue (or an on-disk PortrayalCatalog dir). Moved out of the
//! `tile57` CLI so the CLI is a thin wrapper and any consumer (the C ABI, a Go/JS
//! binding, another UI) can build the same bundle. The tile-bake half (bakeRoot) +
//! the full `bakeBundle` orchestration land here next; this file currently holds the
//! asset emitters. Pure-Zig + libc (the sprite atlas builder needs nanosvg/stb).
//!
//! Each reader takes a `catalog_dir`: "" = the embedded catalogue (catalog module's
//! @embedFile'd registries), else `<catalog_dir>/{Symbols,LineStyles,AreaFills,
//! ColorProfiles}` on disk. The `*Bytes` helpers return the generated bytes (arena
//! owned) so an orchestrator reuses them without re-reading; the `emit*` helpers also
//! write them to a path. I/O is via the caller-supplied `std.Io` (no global state).

const std = @import("std");
const engine = @import("engine");
const assets = @import("assets");
const sprite = @import("sprite");
const embedded_assets = @import("catalog"); // S-101 portrayal assets embedded into the binary

// PortrayalCatalog sub-paths (relative to an on-disk catalog dir).
pub const COLOR_PROFILE_REL = "ColorProfiles/colorProfile.xml";
pub const LINESTYLES_REL = "LineStyles";
pub const SYMBOLS_REL = "Symbols";
pub const AREAFILLS_REL = "AreaFills";
pub const DEFAULT_CSS = "daySvgStyle.css";

// ---- embedded catalogue assets (the `dir == ""` path of the readers) ---------

// Embedded Symbols/*.svg as sprite sources (id = file stem). Sorted at build time.
fn embeddedSymbols(a: std.mem.Allocator) ![]sprite.SvgSrc {
    const out = try a.alloc(sprite.SvgSrc, embedded_assets.symbols.len);
    for (embedded_assets.symbols, 0..) |e, i| out[i] = .{ .id = e.name, .svg = e.bytes };
    return out;
}

// Embedded AreaFills/*.xml as area-fill sources (id = file stem).
fn embeddedFills(a: std.mem.Allocator) ![]sprite.AreaFillSrc {
    const out = try a.alloc(sprite.AreaFillSrc, embedded_assets.areafills.len);
    for (embedded_assets.areafills, 0..) |e, i| out[i] = .{ .id = e.name, .xml = e.bytes };
    return out;
}

// Embedded LineStyles/*.xml as line-style sources (id = file stem).
pub fn embeddedLinestyles(a: std.mem.Allocator) ![]assets.LineStyleSrc {
    const out = try a.alloc(assets.LineStyleSrc, embedded_assets.linestyles.len);
    for (embedded_assets.linestyles, 0..) |e, i| out[i] = .{ .id = e.name, .xml = e.bytes };
    return out;
}

// Build the complex-line tessellation table (id -> LsInfo) from `srcs` and register
// it with s57_mvt before baking, so a named (symbolised) linestyle is drawn as its
// real dash runs + embedded symbols instead of a generic dashed stroke. Mirrors Go
// lsInfoFromCatalog; mm geometry is converted at the PresLib feature scale. Best
// effort — a malformed/short style is simply skipped. `gpa` outlives the bake.
pub fn registerLinestyles(gpa: std.mem.Allocator, srcs: []const assets.LineStyleSrc) void {
    const px = engine.s57_mvt.LINESTYLE_PX_PER_MM;
    for (srcs) |s| {
        const parsed = assets.parseLineStyle(gpa, s.xml) catch continue;
        const period = parsed.interval_length * px;
        if (period < 0.5) continue; // no interval to tile (pure-symbol style)
        var runs = std.ArrayList([2]f64).empty;
        for (parsed.dashes) |d| {
            const lo = d.start * px;
            const hi = (d.start + d.length) * px;
            if (hi - lo > 1e-6) runs.append(gpa, .{ lo, hi }) catch {};
        }
        var syms = std.ArrayList(engine.s57_mvt.LsSym).empty;
        for (parsed.symbols) |sym| syms.append(gpa, .{ .name = sym.reference, .offset_px = sym.position * px }) catch {};
        var width = parsed.pen_width * px;
        if (width < 0.6) width = 0.9; // S-52 minimum pen
        engine.s57_mvt.registerLinestyle(gpa, s.id, .{
            .period_px = period,
            .on_runs = runs.items,
            .symbols = syms.items,
            .color_token = parsed.pen_color,
            .width_px = width,
        });
    }
}

// Embedded palette stylesheet bytes by file name (e.g. "daySvgStyle.css"); the
// lookup is by stem, so callers can pass a bare name. Null if not embedded.
fn embeddedCss(css_name: []const u8) ?[]const u8 {
    const stem = std.fs.path.stem(std.fs.path.basename(css_name));
    for (embedded_assets.css) |e| {
        if (std.mem.eql(u8, e.name, stem)) return e.bytes;
    }
    return null;
}

// The single embedded ColorProfiles/colorProfile.xml, or null if absent.
pub fn embeddedColorProfile() ?[]const u8 {
    for (embedded_assets.colorprofile) |e| return e.bytes;
    return null;
}

// Read the palette CSS: from the embedded catalogue (catalog_dir == "") or from
// <catalog_dir>/Symbols/<css_name> on disk.
fn readCss(io: std.Io, a: std.mem.Allocator, catalog_dir: []const u8, css_name: []const u8) ![]const u8 {
    if (catalog_dir.len == 0) return embeddedCss(css_name) orelse error.MissingCss;
    const css_path = try std.fs.path.join(a, &.{ catalog_dir, SYMBOLS_REL, css_name });
    return std.Io.Dir.cwd().readFileAlloc(io, css_path, a, .unlimited);
}

// Emit colortables.json from a catalog dir. Returns the bytes (arena owned) so an
// orchestrator can reuse them without re-reading. Shared by the assets + bundle paths.
pub fn colorTablesBytes(io: std.Io, a: std.mem.Allocator, catalog_dir: []const u8) ![]u8 {
    const xml = if (catalog_dir.len == 0)
        (embeddedColorProfile() orelse return error.MissingColorProfile)
    else blk: {
        const xml_path = try std.fs.path.join(a, &.{ catalog_dir, COLOR_PROFILE_REL });
        break :blk try std.Io.Dir.cwd().readFileAlloc(io, xml_path, a, .unlimited);
    };
    return assets.colorTablesJson(a, xml);
}

pub fn emitColorTables(io: std.Io, a: std.mem.Allocator, catalog_dir: []const u8, out_path: []const u8) ![]u8 {
    const json = try colorTablesBytes(io, a, catalog_dir);
    try std.Io.Dir.cwd().writeFile(io, .{ .sub_path = out_path, .data = json });
    return json;
}

// Read every LineStyles/*.xml under catalog_dir and emit linestyles.json (dash
// patterns + placed symbols). Returns the bytes (arena owned). Shared by the
// assets + bundle paths. Mirrors the Go oracle's EmitS101 linestyles step.
pub fn linestylesBytes(io: std.Io, a: std.mem.Allocator, catalog_dir: []const u8) ![]u8 {
    if (catalog_dir.len == 0) return assets.linestylesJson(a, try embeddedLinestyles(a));
    const ls_dir_path = try std.fs.path.join(a, &.{ catalog_dir, LINESTYLES_REL });
    var dir = try std.Io.Dir.cwd().openDir(io, ls_dir_path, .{ .iterate = true });
    defer dir.close(io);

    var srcs = std.ArrayList(assets.LineStyleSrc).empty;
    var walker = try dir.walk(a);
    defer walker.deinit();
    while (try walker.next(io)) |entry| {
        if (entry.kind != .file) continue;
        if (!std.mem.endsWith(u8, entry.path, ".xml")) continue;
        const path = try a.dupe(u8, entry.path);
        const xml = dir.readFileAlloc(io, path, a, .unlimited) catch continue;
        const id = std.fs.path.stem(std.fs.path.basename(path));
        try srcs.append(a, .{ .id = id, .xml = xml });
    }
    return assets.linestylesJson(a, srcs.items);
}

pub fn emitLinestyles(io: std.Io, a: std.mem.Allocator, catalog_dir: []const u8, out_path: []const u8) ![]u8 {
    const json = try linestylesBytes(io, a, catalog_dir);
    try std.Io.Dir.cwd().writeFile(io, .{ .sub_path = out_path, .data = json });
    return json;
}

// Read every Symbols/*.svg + the palette CSS and build the sprite atlas
// (sprite.json + sprite.png). Mirrors the Go oracle's SpriteAtlasS101FS.
pub fn spriteAtlasBytes(io: std.Io, a: std.mem.Allocator, catalog_dir: []const u8, css_name: []const u8) !sprite.Atlas {
    const srcs = try readSymbols(io, a, catalog_dir);
    const css = try readCss(io, a, catalog_dir, css_name);
    return sprite.spriteAtlas(a, srcs, css);
}

pub fn emitSprites(io: std.Io, a: std.mem.Allocator, catalog_dir: []const u8, css_name: []const u8, json_path: []const u8, png_path: []const u8) !sprite.Atlas {
    const atlas = try spriteAtlasBytes(io, a, catalog_dir, css_name);
    try std.Io.Dir.cwd().writeFile(io, .{ .sub_path = json_path, .data = atlas.json });
    try std.Io.Dir.cwd().writeFile(io, .{ .sub_path = png_path, .data = atlas.png });
    return atlas;
}

// Read every Symbols/*.svg into a list (shared by the sprite + pattern atlases).
fn readSymbols(io: std.Io, a: std.mem.Allocator, catalog_dir: []const u8) ![]sprite.SvgSrc {
    if (catalog_dir.len == 0) return embeddedSymbols(a);
    const sym_dir_path = try std.fs.path.join(a, &.{ catalog_dir, SYMBOLS_REL });
    var dir = try std.Io.Dir.cwd().openDir(io, sym_dir_path, .{ .iterate = true });
    defer dir.close(io);
    var srcs = std.ArrayList(sprite.SvgSrc).empty;
    var walker = try dir.walk(a);
    defer walker.deinit();
    while (try walker.next(io)) |entry| {
        if (entry.kind != .file) continue;
        if (!std.mem.endsWith(u8, entry.path, ".svg")) continue;
        const path = try a.dupe(u8, entry.path);
        const svg = dir.readFileAlloc(io, path, a, .unlimited) catch continue;
        try srcs.append(a, .{ .id = std.fs.path.stem(std.fs.path.basename(path)), .svg = svg });
    }
    return srcs.items;
}

// Read AreaFills/*.xml + Symbols/*.svg + the palette CSS and build the pattern
// atlas (patterns.json + patterns.png). Mirrors the Go oracle's PatternAtlasS101FS.
pub fn patternAtlasBytes(io: std.Io, a: std.mem.Allocator, catalog_dir: []const u8, css_name: []const u8) !sprite.Atlas {
    const fills = try readFills(io, a, catalog_dir);
    const symbols = try readSymbols(io, a, catalog_dir);
    const css = try readCss(io, a, catalog_dir, css_name);
    return sprite.patternAtlas(a, fills, symbols, css);
}

pub fn emitPatterns(io: std.Io, a: std.mem.Allocator, catalog_dir: []const u8, css_name: []const u8, json_path: []const u8, png_path: []const u8) !sprite.Atlas {
    const atlas = try patternAtlasBytes(io, a, catalog_dir, css_name);
    try std.Io.Dir.cwd().writeFile(io, .{ .sub_path = json_path, .data = atlas.json });
    try std.Io.Dir.cwd().writeFile(io, .{ .sub_path = png_path, .data = atlas.png });
    return atlas;
}

// Read every AreaFills/*.xml under catalog_dir (shared by pattern + sprite-mln).
fn readFills(io: std.Io, a: std.mem.Allocator, catalog_dir: []const u8) ![]sprite.AreaFillSrc {
    if (catalog_dir.len == 0) return embeddedFills(a);
    const af_dir_path = try std.fs.path.join(a, &.{ catalog_dir, AREAFILLS_REL });
    var dir = try std.Io.Dir.cwd().openDir(io, af_dir_path, .{ .iterate = true });
    defer dir.close(io);
    var fills = std.ArrayList(sprite.AreaFillSrc).empty;
    var walker = try dir.walk(a);
    defer walker.deinit();
    while (try walker.next(io)) |entry| {
        if (entry.kind != .file) continue;
        if (!std.mem.endsWith(u8, entry.path, ".xml")) continue;
        const path = try a.dupe(u8, entry.path);
        const xml = dir.readFileAlloc(io, path, a, .unlimited) catch continue;
        try fills.append(a, .{ .id = std.fs.path.stem(std.fs.path.basename(path)), .xml = xml });
    }
    return fills.items;
}

// Build the MapLibre sprite (sprite-mln) directly from the catalogue's Symbols +
// AreaFills + palette CSS. Mirrors the old scripts/build_sprite.py, in Zig.
pub fn spriteMlnBytes(io: std.Io, a: std.mem.Allocator, catalog_dir: []const u8, css_name: []const u8, soundings: []const []const u8) !sprite.Atlas {
    const symbols = try readSymbols(io, a, catalog_dir);
    const fills = try readFills(io, a, catalog_dir);
    const css = try readCss(io, a, catalog_dir, css_name);
    return sprite.spriteMln(a, symbols, fills, css, soundings);
}

// Emit sprite-mln.{json,png} + identical @2x copies (MapLibre requests @2x on
// HiDPI; a missing @2x sheet fails the whole sprite load).
pub fn emitSpriteMln(io: std.Io, a: std.mem.Allocator, catalog_dir: []const u8, css_name: []const u8, out_dir: []const u8, base: []const u8, soundings: []const []const u8) !sprite.Atlas {
    const atlas = try spriteMlnBytes(io, a, catalog_dir, css_name, soundings);
    for ([_][]const u8{ "", "@2x" }) |suffix| {
        const jn = try std.fmt.allocPrint(a, "{s}{s}.json", .{ base, suffix });
        const pn = try std.fmt.allocPrint(a, "{s}{s}.png", .{ base, suffix });
        try std.Io.Dir.cwd().writeFile(io, .{ .sub_path = try std.fs.path.join(a, &.{ out_dir, jn }), .data = atlas.json });
        try std.Io.Dir.cwd().writeFile(io, .{ .sub_path = try std.fs.path.join(a, &.{ out_dir, pn }), .data = atlas.png });
    }
    return atlas;
}
