//! bundle — the chart-bundle pipeline as a LIBRARY module: S-101 portrayal asset
//! emission (colortables / linestyles / sprite / patterns / sprite-mln) built from
//! the embedded catalogue (or an on-disk PortrayalCatalog dir). Moved out of the
//! `tile57` CLI so the CLI is a thin wrapper and any consumer (the C ABI, a Go/JS
//! binding, another UI) can build the same style. Alongside the asset emitters it
//! holds the per-cell composite: the ownership partition + the on-demand tile
//! compositor (composeTile / ComposeSource) that serves a live map from per-cell
//! archives. Pure-Zig + libc (the sprite atlas builder needs nanosvg/stb).
//!
//! Each reader takes a `catalog_dir`: "" = the embedded catalogue (catalog module's
//! @embedFile'd registries), else `<catalog_dir>/{Symbols,LineStyles,AreaFills,
//! ColorProfiles}` on disk. The `*Bytes` helpers return the generated bytes (arena
//! owned) so an orchestrator reuses them without re-reading; the `emit*` helpers also
//! write them to a path. I/O is via the caller-supplied `std.Io` (no global state).

const std = @import("std");
const engine = @import("engine");
const style = @import("style");
const sprite = @import("sprite");
const embedded_assets = @import("catalog"); // S-101 portrayal assets embedded into the binary

// PortrayalCatalog sub-paths (relative to an on-disk catalog dir).
pub const COLOR_PROFILE_REL = "ColorProfiles/colorProfile.xml";
pub const LINESTYLES_REL = "LineStyles";
pub const SYMBOLS_REL = "Symbols";
pub const AREAFILLS_REL = "AreaFills";
pub const DEFAULT_CSS = "daySvgStyle.css";

// ---- embedded catalogue assets (the `dir == ""` path of the readers) ---------

// Embedded Symbols/*.svg as sprite sources (id = file stem). Sorted at build time.
fn embeddedSymbols(a: std.mem.Allocator) ![]sprite.SvgSrc {
    const out = try a.alloc(sprite.SvgSrc, embedded_assets.symbols.len);
    for (embedded_assets.symbols, 0..) |e, i| out[i] = .{ .id = e.name, .svg = e.bytes };
    return out;
}

// Embedded AreaFills/*.xml as area-fill sources (id = file stem).
fn embeddedFills(a: std.mem.Allocator) ![]sprite.AreaFillSrc {
    const out = try a.alloc(sprite.AreaFillSrc, embedded_assets.areafills.len);
    for (embedded_assets.areafills, 0..) |e, i| out[i] = .{ .id = e.name, .xml = e.bytes };
    return out;
}

// Embedded LineStyles/*.xml as line-style sources (id = file stem).
pub fn embeddedLinestyles(a: std.mem.Allocator) ![]style.LineStyleSrc {
    const out = try a.alloc(style.LineStyleSrc, embedded_assets.linestyles.len);
    for (embedded_assets.linestyles, 0..) |e, i| out[i] = .{ .id = e.name, .xml = e.bytes };
    return out;
}

// Build the complex-line tessellation table (id -> LsInfo) from `srcs` and register
// it with scene before baking, so a named (symbolised) linestyle is drawn as its
// real dash runs + embedded symbols instead of a generic dashed stroke. Mirrors Go
// lsInfoFromCatalog; mm geometry is converted at the PresLib feature scale. Best
// effort — a malformed/short style is simply skipped. `gpa` outlives the bake.
pub fn registerLinestyles(gpa: std.mem.Allocator, srcs: []const style.LineStyleSrc) void {
    const px = engine.scene.LINESTYLE_PX_PER_MM;
    for (srcs) |s| {
        const parsed = style.parseLineStyle(gpa, s.xml) catch continue;
        const period = parsed.interval_length * px;
        if (period < 0.5) continue; // no interval to tile (pure-symbol style)
        var runs = std.ArrayList([2]f64).empty;
        for (parsed.dashes) |d| {
            const lo = d.start * px;
            const hi = (d.start + d.length) * px;
            if (hi - lo > 1e-6) runs.append(gpa, .{ lo, hi }) catch {};
        }
        var syms = std.ArrayList(engine.scene.LsSym).empty;
        for (parsed.symbols) |sym| syms.append(gpa, .{ .name = sym.reference, .offset_px = sym.position * px }) catch {};
        var width = parsed.pen_width * px;
        if (width < 0.6) width = 0.9; // S-52 minimum pen
        engine.scene.registerLinestyle(gpa, s.id, .{
            .period_px = period,
            .on_runs = runs.items,
            .symbols = syms.items,
            .color_token = parsed.pen_color,
            .width_px = width,
        });
    }
}

// Embedded palette stylesheet bytes by file name (e.g. "daySvgStyle.css"); the
// lookup is by stem, so callers can pass a bare name. Null if not embedded.
fn embeddedCss(css_name: []const u8) ?[]const u8 {
    const stem = std.fs.path.stem(std.fs.path.basename(css_name));
    for (embedded_assets.css) |e| {
        if (std.mem.eql(u8, e.name, stem)) return e.bytes;
    }
    return null;
}

// The single embedded ColorProfiles/colorProfile.xml, or null if absent.
pub fn embeddedColorProfile() ?[]const u8 {
    for (embedded_assets.colorprofile) |e| return e.bytes;
    return null;
}

// Read the palette CSS: from the embedded catalogue (catalog_dir == "") or from
// <catalog_dir>/Symbols/<css_name> on disk.
fn readCss(io: std.Io, a: std.mem.Allocator, catalog_dir: []const u8, css_name: []const u8) ![]const u8 {
    if (catalog_dir.len == 0) return embeddedCss(css_name) orelse error.MissingCss;
    const css_path = try std.fs.path.join(a, &.{ catalog_dir, SYMBOLS_REL, css_name });
    return std.Io.Dir.cwd().readFileAlloc(io, css_path, a, .unlimited);
}

// Emit colortables.json from a catalog dir. Returns the bytes (arena owned) so an
// orchestrator can reuse them without re-reading. Shared by the assets + bundle paths.
pub fn colorTablesBytes(io: std.Io, a: std.mem.Allocator, catalog_dir: []const u8) ![]u8 {
    const xml = if (catalog_dir.len == 0)
        (embeddedColorProfile() orelse return error.MissingColorProfile)
    else blk: {
        const xml_path = try std.fs.path.join(a, &.{ catalog_dir, COLOR_PROFILE_REL });
        break :blk try std.Io.Dir.cwd().readFileAlloc(io, xml_path, a, .unlimited);
    };
    return style.colorTablesJson(a, xml);
}

pub fn emitColorTables(io: std.Io, a: std.mem.Allocator, catalog_dir: []const u8, out_path: []const u8) ![]u8 {
    const json = try colorTablesBytes(io, a, catalog_dir);
    try std.Io.Dir.cwd().writeFile(io, .{ .sub_path = out_path, .data = json });
    return json;
}

// Read every LineStyles/*.xml under catalog_dir and emit linestyles.json (dash
// patterns + placed symbols). Returns the bytes (arena owned). Shared by the
// assets + bundle paths. Mirrors the Go oracle's EmitS101 linestyles step.
pub fn linestylesBytes(io: std.Io, a: std.mem.Allocator, catalog_dir: []const u8) ![]u8 {
    if (catalog_dir.len == 0) return style.linestylesJson(a, try embeddedLinestyles(a));
    const ls_dir_path = try std.fs.path.join(a, &.{ catalog_dir, LINESTYLES_REL });
    var dir = try std.Io.Dir.cwd().openDir(io, ls_dir_path, .{ .iterate = true });
    defer dir.close(io);

    var srcs = std.ArrayList(style.LineStyleSrc).empty;
    var walker = try dir.walk(a);
    defer walker.deinit();
    while (try walker.next(io)) |entry| {
        if (entry.kind != .file) continue;
        if (!std.mem.endsWith(u8, entry.path, ".xml")) continue;
        const path = try a.dupe(u8, entry.path);
        const xml = dir.readFileAlloc(io, path, a, .unlimited) catch continue;
        const id = std.fs.path.stem(std.fs.path.basename(path));
        try srcs.append(a, .{ .id = id, .xml = xml });
    }
    return style.linestylesJson(a, srcs.items);
}

pub fn emitLinestyles(io: std.Io, a: std.mem.Allocator, catalog_dir: []const u8, out_path: []const u8) ![]u8 {
    const json = try linestylesBytes(io, a, catalog_dir);
    try std.Io.Dir.cwd().writeFile(io, .{ .sub_path = out_path, .data = json });
    return json;
}

// Read every Symbols/*.svg + the palette CSS and build the sprite atlas
// (sprite.json + sprite.png). Mirrors the Go oracle's SpriteAtlasS101FS.
pub fn spriteAtlasBytes(io: std.Io, a: std.mem.Allocator, catalog_dir: []const u8, css_name: []const u8) !sprite.Atlas {
    const srcs = try readSymbols(io, a, catalog_dir);
    const css = try readCss(io, a, catalog_dir, css_name);
    return sprite.spriteAtlas(a, srcs, css);
}

pub fn emitSprites(io: std.Io, a: std.mem.Allocator, catalog_dir: []const u8, css_name: []const u8, json_path: []const u8, png_path: []const u8) !sprite.Atlas {
    const atlas = try spriteAtlasBytes(io, a, catalog_dir, css_name);
    try std.Io.Dir.cwd().writeFile(io, .{ .sub_path = json_path, .data = atlas.json });
    try std.Io.Dir.cwd().writeFile(io, .{ .sub_path = png_path, .data = atlas.png });
    return atlas;
}

// Read every Symbols/*.svg into a list (shared by the sprite + pattern atlases).
fn readSymbols(io: std.Io, a: std.mem.Allocator, catalog_dir: []const u8) ![]sprite.SvgSrc {
    if (catalog_dir.len == 0) return embeddedSymbols(a);
    const sym_dir_path = try std.fs.path.join(a, &.{ catalog_dir, SYMBOLS_REL });
    var dir = try std.Io.Dir.cwd().openDir(io, sym_dir_path, .{ .iterate = true });
    defer dir.close(io);
    var srcs = std.ArrayList(sprite.SvgSrc).empty;
    var walker = try dir.walk(a);
    defer walker.deinit();
    while (try walker.next(io)) |entry| {
        if (entry.kind != .file) continue;
        if (!std.mem.endsWith(u8, entry.path, ".svg")) continue;
        const path = try a.dupe(u8, entry.path);
        const svg = dir.readFileAlloc(io, path, a, .unlimited) catch continue;
        try srcs.append(a, .{ .id = std.fs.path.stem(std.fs.path.basename(path)), .svg = svg });
    }
    return srcs.items;
}

// Read AreaFills/*.xml + Symbols/*.svg + the palette CSS and build the pattern
// atlas (patterns.json + patterns.png). Mirrors the Go oracle's PatternAtlasS101FS.
pub fn patternAtlasBytes(io: std.Io, a: std.mem.Allocator, catalog_dir: []const u8, css_name: []const u8) !sprite.Atlas {
    const fills = try readFills(io, a, catalog_dir);
    const symbols = try readSymbols(io, a, catalog_dir);
    const css = try readCss(io, a, catalog_dir, css_name);
    return sprite.patternAtlas(a, fills, symbols, css);
}

pub fn emitPatterns(io: std.Io, a: std.mem.Allocator, catalog_dir: []const u8, css_name: []const u8, json_path: []const u8, png_path: []const u8) !sprite.Atlas {
    const atlas = try patternAtlasBytes(io, a, catalog_dir, css_name);
    try std.Io.Dir.cwd().writeFile(io, .{ .sub_path = json_path, .data = atlas.json });
    try std.Io.Dir.cwd().writeFile(io, .{ .sub_path = png_path, .data = atlas.png });
    return atlas;
}

// Read every AreaFills/*.xml under catalog_dir (shared by pattern + sprite-mln).
fn readFills(io: std.Io, a: std.mem.Allocator, catalog_dir: []const u8) ![]sprite.AreaFillSrc {
    if (catalog_dir.len == 0) return embeddedFills(a);
    const af_dir_path = try std.fs.path.join(a, &.{ catalog_dir, AREAFILLS_REL });
    var dir = try std.Io.Dir.cwd().openDir(io, af_dir_path, .{ .iterate = true });
    defer dir.close(io);
    var fills = std.ArrayList(sprite.AreaFillSrc).empty;
    var walker = try dir.walk(a);
    defer walker.deinit();
    while (try walker.next(io)) |entry| {
        if (entry.kind != .file) continue;
        if (!std.mem.endsWith(u8, entry.path, ".xml")) continue;
        const path = try a.dupe(u8, entry.path);
        const xml = dir.readFileAlloc(io, path, a, .unlimited) catch continue;
        try fills.append(a, .{ .id = std.fs.path.stem(std.fs.path.basename(path)), .xml = xml });
    }
    return fills.items;
}

// Build the MapLibre sprite (sprite-mln) directly from the catalogue's Symbols +
// AreaFills + palette CSS. Mirrors the old scripts/build_sprite.py, in Zig.
pub fn spriteMlnBytes(io: std.Io, a: std.mem.Allocator, catalog_dir: []const u8, css_name: []const u8, soundings: []const []const u8) !sprite.Atlas {
    const symbols = try readSymbols(io, a, catalog_dir);
    const fills = try readFills(io, a, catalog_dir);
    const css = try readCss(io, a, catalog_dir, css_name);
    return sprite.spriteMln(a, symbols, fills, css, soundings);
}

// Emit sprite-mln.{json,png} + identical @2x copies (MapLibre requests @2x on
// HiDPI; a missing @2x sheet fails the whole sprite load).
pub fn emitSpriteMln(io: std.Io, a: std.mem.Allocator, catalog_dir: []const u8, css_name: []const u8, out_dir: []const u8, base: []const u8, soundings: []const []const u8) !sprite.Atlas {
    const atlas = try spriteMlnBytes(io, a, catalog_dir, css_name, soundings);
    for ([_][]const u8{ "", "@2x" }) |suffix| {
        const jn = try std.fmt.allocPrint(a, "{s}{s}.json", .{ base, suffix });
        const pn = try std.fmt.allocPrint(a, "{s}{s}.png", .{ base, suffix });
        try std.Io.Dir.cwd().writeFile(io, .{ .sub_path = try std.fs.path.join(a, &.{ out_dir, jn }), .data = atlas.json });
        try std.Io.Dir.cwd().writeFile(io, .{ .sub_path = try std.fs.path.join(a, &.{ out_dir, pn }), .data = atlas.png });
    }
    return atlas;
}

// Read + parse one cell (base .000 + sequential updates) from `dir`; null on
// any failure. The parsed cell allocates from smp_allocator (thread-safe).
fn readParseCell(io: std.Io, dir: std.Io.Dir, bpath: []const u8) ?engine.s57.Cell {
    const gpa = std.heap.smp_allocator;
    const base = dir.readFileAlloc(io, bpath, gpa, .unlimited) catch return null;
    defer gpa.free(base);
    if (base.len == 0) return null;
    var ups = std.ArrayList([]const u8).empty;
    defer {
        for (ups.items) |ub| gpa.free(ub);
        ups.deinit(gpa);
    }
    const stem = bpath[0 .. bpath.len - 4];
    var u: u32 = 1;
    while (u <= 999) : (u += 1) {
        const upn = std.fmt.allocPrint(gpa, "{s}.{d:0>3}", .{ stem, u }) catch break;
        defer gpa.free(upn);
        const ub = dir.readFileAlloc(io, upn, gpa, .unlimited) catch break;
        ups.append(gpa, ub) catch {
            gpa.free(ub);
            break;
        };
    }
    return engine.s57.parseCellWithUpdates(gpa, base, ups.items) catch null;
}

/// One ENC cell loaded for coverage-level work: its M_COVR(CATCOV=1) rings, bbox,
/// compilation scale, DSNM stem, and DSID date. The eager cell-loader's output; the
/// cross-pack context uses a subset, the partition debug bake widens it to points.
pub const LoadedCov = struct {
    name: []const u8, // DSNM stem
    date: []const u8, // DSID issue/update date (YYYYMMDD)
    cscl: i32, // compilation scale (1:N)
    coverage: []const []const []const engine.s57.LonLat, // M_COVR(CATCOV=1) rings
    bounds: [4]f64, // [w,s,e,n] over the coverage
};

/// THE eager cell-coverage loader: walk an ENC_ROOT, parse each cell once (base +
/// updates via readParseCell), and capture its M_COVR coverage + bbox + cscl + name
/// + date. One entry per stem (a boundary cell shared by two districts loads once).
/// Coverage is copied into `a` and survives the cell's deinit. "" / a missing dir
/// yields none; cells with no M_COVR are skipped. The single load path composed by
/// the cross-pack context, the partition debug bake, and the compositor.
fn loadCells(io: std.Io, a: std.mem.Allocator, path: []const u8) []LoadedCov {
    if (path.len == 0) return &.{};
    var dir = std.Io.Dir.cwd().openDir(io, path, .{ .iterate = true }) catch return &.{};
    defer dir.close(io);
    var out = std.ArrayList(LoadedCov).empty;
    var seen = std.StringHashMap(void).init(a);
    var walker = dir.walk(a) catch return &.{};
    defer walker.deinit();
    while (walker.next(io) catch null) |entry| {
        if (entry.kind != .file or !std.mem.endsWith(u8, entry.path, ".000")) continue;
        const stem = std.fs.path.stem(std.fs.path.basename(entry.path));
        if (seen.contains(stem)) continue;
        const stem_d = a.dupe(u8, stem) catch continue;
        seen.put(stem_d, {}) catch {};

        var cell = readParseCell(io, dir, entry.path) orelse continue;
        defer cell.deinit();
        const cov = cell.mcovrCoverage(a); // copied into `a`; survives cell.deinit()
        if (cov.len == 0) continue;
        var b = [4]f64{ 1e9, 1e9, -1e9, -1e9 };
        for (cov) |rings| for (rings) |ring| for (ring) |p| {
            b[0] = @min(b[0], p.lon());
            b[1] = @min(b[1], p.lat());
            b[2] = @max(b[2], p.lon());
            b[3] = @max(b[3], p.lat());
        };
        out.append(a, .{
            .name = stem_d,
            .date = a.dupe(u8, cell.dsid.isdt) catch "",
            .cscl = cell.params.cscl,
            .coverage = cov,
            .bounds = b,
        }) catch {};
    }
    return out.toOwnedSlice(a) catch &.{};
}

// A cyclic palette so adjacent ownership faces get distinct colours in the debug
// view; a face carries its colour as a `color` property for a trivial data-driven style.
const DEBUG_PALETTE = [_][]const u8{
    "#e6194b", "#3cb44b", "#ffe119", "#4363d8", "#f58231", "#911eb4", "#46f0f0", "#f032e6",
    "#bcf60c", "#fabebe", "#008080", "#e6beff", "#9a6324", "#fffac8", "#800000", "#aaffc3",
};

/// Bake a DEBUG PMTiles of the ownership PARTITION (which cell renders which ground),
/// NO portrayed content, for eyeballing the composite quilt. `band` < 0 emits the band
/// GOVERNING each zoom (the natural view); 0..5 (berthing..overview) emits only that
/// band's own map, at every zoom. Composes the single paths — loadCells + toPlaneCells
/// + geometry.plane partition + the mvt/tile/pmtiles primitives — and STREAMS tiles (one
/// tier + one zoom resident) so it scales to the whole corpus. Returns the cell count;
/// `out_path` is a single `.pmtiles` file.
pub fn bakePartitionDebug(io: std.Io, gpa: std.mem.Allocator, root_path: []const u8, out_path: []const u8, minzoom: u8, maxzoom_arg: u8, band: i8) !usize {
    const geometry = engine.geometry;
    const maxzoom = @min(maxzoom_arg, @as(u8, 16));

    var arena = std.heap.ArenaAllocator.init(gpa);
    defer arena.deinit();
    const a = arena.allocator();

    // Single load + adapt paths. Reach-cap each cell exactly as the compositor does
    // (band terms only — a native per-cell bake never exceeds its band window), so the
    // debug quilt shows the partition the compositor actually composes with, not a
    // hypothetical full pool.
    const loaded = loadCells(io, a, root_path);
    if (loaded.len == 0) return error.NoGeometry;
    const cells = try toPlaneCells(a, loaded);
    for (cells) |*c| c.reach = bandReach(c.cscl);

    // Union bbox (E7) for the header, so a viewer opens on the data not the world.
    var ubox = [4]i32{ std.math.maxInt(i32), std.math.maxInt(i32), std.math.minInt(i32), std.math.minInt(i32) };
    for (loaded) |c| {
        ubox[0] = @min(ubox[0], deg7(c.bounds[0]));
        ubox[1] = @min(ubox[1], deg7(c.bounds[1]));
        ubox[2] = @max(ubox[2], deg7(c.bounds[2]));
        ubox[3] = @max(ubox[3], deg7(c.bounds[3]));
    }
    std.debug.print("partition-debug: {d} cells from {s}, z{d}-{d}, band {d}\n", .{ loaded.len, root_path, minzoom, maxzoom, band });

    // Stream tiles (gzipped + deduped) so the whole archive never lives uncompressed.
    var sw = engine.pmtiles.StreamWriter.init(gpa);
    defer sw.deinit();
    var zoom_arena = std.heap.ArenaAllocator.init(gpa); // one zoom's tiles at a time
    defer zoom_arena.deinit();

    if (band >= 0) {
        // One band's own map: build its tier once, emit across every zoom.
        const bandv: engine.bake_enc.Band = @enumFromInt(@as(u8, @intCast(@min(band, @as(i8, 5)))));
        const tier = engine.bake_enc.bandZooms(bandv).min;
        const faces = try geometry.plane.ownedAtTierIndexed(gpa, cells, tier);
        defer geometry.plane.freeOwned(gpa, faces);
        var z: u8 = minzoom;
        while (z <= maxzoom) : (z += 1) {
            _ = zoom_arena.reset(.retain_capacity);
            try emitFacesZoom(&sw, zoom_arena.allocator(), faces, loaded, z, tier);
        }
    } else {
        // Merged: the band governing each zoom. Build that tier lazily, one resident at
        // a time (coarse→fine as z rises), so the finest tier is only built if reached.
        const floors = try distinctFloorsDesc(a, cells);
        var cur_tier: i16 = -1;
        var cur_faces: []geometry.plane.OwnedCell = &.{};
        defer if (cur_tier >= 0) geometry.plane.freeOwned(gpa, cur_faces);
        var z: u8 = minzoom;
        while (z <= maxzoom) : (z += 1) {
            const t = governingTier(floors, z);
            if (cur_tier != @as(i16, t)) {
                if (cur_tier >= 0) geometry.plane.freeOwned(gpa, cur_faces);
                cur_faces = try geometry.plane.ownedAtTierIndexed(gpa, cells, t);
                cur_tier = t;
            }
            _ = zoom_arena.reset(.retain_capacity);
            try emitFacesZoom(&sw, zoom_arena.allocator(), cur_faces, loaded, z, t);
        }
    }

    // Frame a viewer on the data (a zoom where the bbox is ~2 tiles wide).
    const span_deg = @max(0.01, @as(f64, @floatFromInt(ubox[2] - ubox[0])) / 1e7);
    const cz: u8 = @intFromFloat(std.math.clamp(std.math.log2(720.0 / span_deg), @as(f64, @floatFromInt(minzoom)), @as(f64, @floatFromInt(maxzoom))));
    const bytes = try sw.finishBytes(.{
        // MapLibre/pmtiles.io build their style from `vector_layers`; without it the
        // "partition" layer is invisible to a viewer no matter the geometry.
        .metadata_json = "{\"name\":\"partition-debug\",\"format\":\"pbf\",\"vector_layers\":[{\"id\":\"partition\",\"fields\":{\"cell\":\"String\",\"cscl\":\"Number\",\"band\":\"Number\",\"tier\":\"Number\",\"oi\":\"Number\",\"color\":\"String\"}},{\"id\":\"labels\",\"fields\":{\"cell\":\"String\"}}]}",
        .tile_type = .mvt,
        .min_lon_e7 = ubox[0],
        .min_lat_e7 = ubox[1],
        .max_lon_e7 = ubox[2],
        .max_lat_e7 = ubox[3],
        .center_zoom = cz,
    });
    defer gpa.free(bytes);
    try std.Io.Dir.cwd().writeFile(io, .{ .sub_path = out_path, .data = bytes });
    return loaded.len;
}

// deg → E7 integer.
fn deg7(d: f64) i32 {
    return @intFromFloat(@round(d * 1e7));
}

// Distinct band floors, DESCENDING (finest floor first) — the tier ladder.
fn distinctFloorsDesc(a: std.mem.Allocator, cells: []const engine.geometry.plane.Cell) ![]u8 {
    var seen = std.AutoHashMap(u8, void).init(a);
    for (cells) |c| try seen.put(c.band_floor, {});
    const out = try a.alloc(u8, seen.count());
    var it = seen.keyIterator();
    var i: usize = 0;
    while (it.next()) |k| : (i += 1) out[i] = k.*;
    std.mem.sort(u8, out, {}, comptime std.sort.desc(u8));
    return out;
}

// The band floor governing zoom `z`: the largest floor ≤ z, or the coarsest if z is
// below every floor (so zooming out never falls off the bottom).
fn governingTier(floors_desc: []const u8, z: u8) u8 {
    for (floors_desc) |t| if (t <= z) return t;
    return floors_desc[floors_desc.len - 1];
}

/// The s57-coverage → geometry.plane.Cell adapter: widen each cell's M_COVR to integer
/// points, set the band floor (bandOf), and assign the deterministic DSID order (same
/// tie-break as the bake) across the whole set. Arena-allocated in `a`. THE single
/// conversion path; the partition-debug bake and the compositor both use it.
fn toPlaneCells(a: std.mem.Allocator, loaded: []const LoadedCov) ![]engine.geometry.plane.Cell {
    const geometry = engine.geometry;
    const n = loaded.len;
    const rank = try a.alloc(usize, n);
    for (rank, 0..) |*v, i| v.* = i;
    std.mem.sort(usize, rank, loaded, struct {
        fn lt(ls: []const LoadedCov, x: usize, y: usize) bool {
            return engine.bake_enc.ordersBeforeKeys(ls[x].date, ls[x].name, ls[y].date, ls[y].name);
        }
    }.lt);
    const order = try a.alloc(u64, n);
    for (rank, 0..) |ci, r| order[ci] = r;

    const cells = try a.alloc(geometry.plane.Cell, n);
    for (loaded, 0..) |lc, i| {
        const out = try a.alloc(geometry.plane.Poly, lc.coverage.len);
        for (lc.coverage, 0..) |feat, fi| {
            const rings = try a.alloc([]const geometry.plane.Pt, feat.len);
            for (feat, 0..) |ring, ri| {
                const pts = try a.alloc(geometry.plane.Pt, ring.len);
                for (ring, 0..) |p, pi| pts[pi] = .{ .x = p.lon_e7, .y = p.lat_e7 };
                rings[ri] = pts;
            }
            out[fi] = rings;
        }
        cells[i] = .{
            .cscl = lc.cscl,
            .band_floor = engine.bake_enc.bandZooms(engine.bake_enc.bandOf(lc.cscl)).min,
            .order = order[i],
            .cov1 = out,
        };
    }
    return cells;
}

/// Project + clip one tier's faces into the tiles of zoom `z` and stream them to `sw`
/// (layer "partition"). `sa` is a per-zoom arena the caller resets, so only one zoom's
/// tiles are resident. Reuses tile.project/clipPolygon + scene.orientAreaRings (the MVT
/// winding authority) + mvt.encode.
fn emitFacesZoom(sw: *engine.pmtiles.StreamWriter, sa: std.mem.Allocator, faces: []const engine.geometry.plane.OwnedCell, loaded: []const LoadedCov, z: u8, tier: u8) !void {
    const mvt = engine.mvt;
    const tile = engine.tile;
    const scale: f64 = @floatFromInt(@as(u64, 1) << @intCast(z));
    const TileKey = struct { x: u32, y: u32 };
    const TileFeat = struct { polys: std.ArrayList(mvt.Feature), labels: std.ArrayList(mvt.Feature) };
    var tilemap = std.AutoHashMap(TileKey, TileFeat).init(sa);

    for (faces) |face| {
        if (face.owned.len == 0) continue;
        const lc = loaded[face.index];

        var fb = [4]f64{ 1e9, 1e9, -1e9, -1e9 };
        for (face.owned) |ring| for (ring) |p| {
            const lon = @as(f64, @floatFromInt(p.x)) / 1e7;
            const lat = @as(f64, @floatFromInt(p.y)) / 1e7;
            fb[0] = @min(fb[0], lon);
            fb[1] = @min(fb[1], lat);
            fb[2] = @max(fb[2], lon);
            fb[3] = @max(fb[3], lat);
        };
        const w_tl = tile.lonLatToWorld(fb[0], fb[3]);
        const w_br = tile.lonLatToWorld(fb[2], fb[1]);
        const tx0 = worldAxisToTile(w_tl[0], scale);
        const tx1 = worldAxisToTile(w_br[0], scale);
        const ty0 = worldAxisToTile(w_tl[1], scale);
        const ty1 = worldAxisToTile(w_br[1], scale);

        const props = try sa.dupe(mvt.Prop, &.{
            .{ .key = "cell", .value = .{ .string = lc.name } },
            .{ .key = "cscl", .value = .{ .int = lc.cscl } },
            .{ .key = "band", .value = .{ .int = @intFromEnum(engine.bake_enc.bandOf(lc.cscl)) } },
            .{ .key = "tier", .value = .{ .int = tier } },
            .{ .key = "oi", .value = .{ .int = @intCast(face.index) } },
            .{ .key = "color", .value = .{ .string = DEBUG_PALETTE[face.index % DEBUG_PALETTE.len] } },
        });

        var tx = tx0;
        while (tx <= tx1) : (tx += 1) {
            var ty = ty0;
            while (ty <= ty1) : (ty += 1) {
                var parts = std.ArrayList([]const mvt.Point).empty;
                for (face.owned) |ring| {
                    const proj = try sa.alloc(mvt.Point, ring.len);
                    for (ring, 0..) |p, k| proj[k] = tile.project(@as(f64, @floatFromInt(p.x)) / 1e7, @as(f64, @floatFromInt(p.y)) / 1e7, z, tx, ty, tile.EXTENT);
                    const clipped = try tile.clipPolygon(sa, proj, tile.Box.default(tile.EXTENT, 256));
                    if (clipped.len >= 3) try parts.append(sa, clipped);
                }
                if (parts.items.len == 0) continue;
                const oriented = try engine.mvt.orientAreaRings(sa, parts.items);
                const gop = try tilemap.getOrPut(.{ .x = tx, .y = ty });
                if (!gop.found_existing) gop.value_ptr.* = .{ .polys = .empty, .labels = .empty };
                try gop.value_ptr.polys.append(sa, .{ .geom_type = .polygon, .parts = oriented, .properties = props });

                // Label this face's part IN THIS tile, at the centre of its clipped
                // extent, so the owning cell name is readable wherever the face shows
                // (layer "labels"). MapLibre collision-dedups the repeats across tiles.
                var lb = [4]i32{ std.math.maxInt(i32), std.math.maxInt(i32), std.math.minInt(i32), std.math.minInt(i32) };
                for (oriented) |ring| for (ring) |p| {
                    lb[0] = @min(lb[0], p.x);
                    lb[1] = @min(lb[1], p.y);
                    lb[2] = @max(lb[2], p.x);
                    lb[3] = @max(lb[3], p.y);
                };
                const lpt = try sa.alloc(mvt.Point, 1);
                lpt[0] = .{ .x = @divTrunc(lb[0] + lb[2], 2), .y = @divTrunc(lb[1] + lb[3], 2) };
                const lparts = try sa.alloc([]const mvt.Point, 1);
                lparts[0] = lpt;
                try gop.value_ptr.labels.append(sa, .{ .geom_type = .point, .parts = lparts, .properties = try sa.dupe(mvt.Prop, &.{.{ .key = "cell", .value = .{ .string = lc.name } }}) });
            }
        }
    }

    var it = tilemap.iterator();
    while (it.next()) |kv| {
        var layers = std.ArrayList(mvt.Layer).empty;
        if (kv.value_ptr.polys.items.len > 0) try layers.append(sa, .{ .name = "partition", .features = kv.value_ptr.polys.items });
        if (kv.value_ptr.labels.items.len > 0) try layers.append(sa, .{ .name = "labels", .features = kv.value_ptr.labels.items });
        if (layers.items.len == 0) continue;
        const enc = try mvt.encode(sa, .{ .layers = layers.items });
        try sw.add(z, kv.key_ptr.x, kv.key_ptr.y, enc);
    }
}

// A normalised web-mercator world axis coordinate ([0,1]) → tile index at `scale`
// (= 2^z), clamped to [0, scale-1].
fn worldAxisToTile(w: f64, scale: f64) u32 {
    const f = @floor(w * scale);
    if (f < 0) return 0;
    return @intFromFloat(@min(f, scale - 1));
}

// ===========================================================================
// Per-cell composite — the on-demand tile compositor
// ===========================================================================
//
// Combine N per-cell PMTiles (each native-band-scale, its M_COVR coverage embedded in the
// metadata) into ONE merged PMTiles driven by the ownership partition. At every output tile,
// each owning cell's decoded features are clipped to the ground it OWNS (partition.ownedFace,
// projected into the tile) and concatenated per layer. The faces are a disjoint partition, so
// there is no double-draw at a seam and no z-order re-sort — S-52 draw priority rides the
// per-feature `draw_prio` property, which the style sorts client-side (so feature order within
// a tile is cosmetic). This retires the streaming in-bake cross-cell combiner: the per-cell
// bakes stay dumb + cacheable, and all cross-cell logic is precomputed as the partition.

const N_COMPOSE_LAYERS = engine.mvt.VECTOR_LAYERS.len;

// The tile-index cover (nw..se) of an owner face's lon/lat bbox at zoom `scale = 1<<z`. The
// on-demand composeTile culls candidate tiles through this exact box.
const TileBBox = struct { tx0: u32, tx1: u32, ty0: u32, ty1: u32 };
fn faceTileBBox(face: engine.geometry.plane.OwnedCell, scale: f64) TileBBox {
    const tile = engine.tile;
    var fb = [4]f64{ 1e9, 1e9, -1e9, -1e9 };
    for (face.owned) |ring| for (ring) |p| {
        const lon = @as(f64, @floatFromInt(p.x)) / 1e7;
        const lat = @as(f64, @floatFromInt(p.y)) / 1e7;
        fb[0] = @min(fb[0], lon);
        fb[1] = @min(fb[1], lat);
        fb[2] = @max(fb[2], lon);
        fb[3] = @max(fb[3], lat);
    };
    const w_tl = tile.lonLatToWorld(fb[0], fb[3]); // NW: min lon, max lat
    const w_br = tile.lonLatToWorld(fb[2], fb[1]); // SE: max lon, min lat
    return .{
        .tx0 = worldAxisToTile(w_tl[0], scale),
        .tx1 = worldAxisToTile(w_br[0], scale),
        .ty0 = worldAxisToTile(w_tl[1], scale),
        .ty1 = worldAxisToTile(w_br[1], scale),
    };
}

// The classifier's owned-face grid cell width at zoom z, in integer lon/lat (deg × 1e7).
fn tileWidthE7(z: u8) i64 {
    return @max(1, @divFloor(@as(i64, 3_600_000_000), @as(i64, 1) << @intCast(z)));
}

// The (z,tx,ty) box expanded by the render BUFFER, in integer lon/lat — the region a verbatim
// passthrough must fully own (tile AND its buffer) before it fires.
fn tileClassifyBox(z: u8, tx: u32, ty: u32) engine.geometry.plane.Box {
    const tile = engine.tile;
    const tb = tile.tileBoundsLonLat(z, tx, ty); // [min_lon, min_lat, max_lon, max_lat]
    const lon0: i64 = @intFromFloat(@round(tb[0] * 1e7));
    const lat0: i64 = @intFromFloat(@round(tb[1] * 1e7));
    const lon1: i64 = @intFromFloat(@round(tb[2] * 1e7));
    const lat1: i64 = @intFromFloat(@round(tb[3] * 1e7));
    const bufx = @divTrunc((lon1 - lon0) * @as(i64, tile.BUFFER), @as(i64, tile.EXTENT));
    const bufy = @divTrunc((lat1 - lat0) * @as(i64, tile.BUFFER), @as(i64, tile.EXTENT));
    return .{ .min_x = lon0 - bufx, .min_y = lat0 - bufy, .max_x = lon1 + bufx, .max_y = lat1 + bufy };
}

// Compose one seam/overscale tile from its contributing owner slots (in face order) into raw MLT
// bytes, or null if nothing survives the clip. Decode each owner's tile (native or overscaled
// ancestor), clip its features to the owner's projected owned face, per-layer concat in
// VECTOR_LAYERS order, re-orient polygons, encode. `ta` is a per-tile scratch allocator. Shared by
// the batch pass 2 and the on-demand composeTile, so both emit byte-identical tiles.
fn composeSeamTile(ta: std.mem.Allocator, part: *const engine.geometry.partition.Partition, map: *const engine.geometry.partition.BandMap, readers: []const *engine.pmtiles.Reader, slots: []const u32, z: u8, tx: u32, ty: u32) !?[]u8 {
    const mvt = engine.mvt;
    const compose = engine.scene.compose;
    var buckets: [N_COMPOSE_LAYERS]std.ArrayList(mvt.Feature) = undefined;
    for (&buckets) |*b| b.* = std.ArrayList(mvt.Feature).empty;
    for (slots) |slot| {
        const face = map.faces[slot];
        const ci = face.index;
        const layers = (try ownerTile(ta, readers[ci], part.cells[ci].cscl, z, tx, ty)) orelse continue;
        const face_px = try compose.projectFace(ta, face.owned, z, tx, ty);
        if (face_px.len == 0) continue;
        for (layers) |layer| {
            const li = layerIndex(layer.name) orelse continue;
            for (layer.features) |feat| try compose.clipFeatureToFace(ta, &buckets[li], feat, face_px);
        }
    }
    var out_layers = std.ArrayList(engine.mvt.Layer).empty;
    for (&buckets, 0..) |*bucket, li| {
        if (bucket.items.len == 0) continue;
        const feats = try orientPolys(ta, bucket.items);
        try out_layers.append(ta, .{ .name = engine.mvt.VECTOR_LAYERS[li], .features = feats });
    }
    if (out_layers.items.len == 0) return null;
    return try engine.mlt.encode(ta, .{ .layers = out_layers.items });
}

/// Compose ONE tile on demand from a resident partition + mmap'd per-cell `readers` (cell index ==
/// reader index, exactly as openComposeSourceFiles aligns them). `gzip` = true returns the gzipped MLT the
/// batch archive stores (byte-identical to it — a verbatim owner blob copied verbatim, or a freshly
/// composed seam tile re-gzipped); `gzip` = false returns the raw decompressed MLT (what a live tile
/// server wants — the HTTP layer gzips on the wire). gpa-owned; null if no cell owns this tile. This
/// is the runtime compositor: with the partition loaded once, serving a tile is a classify plus
/// either one memcpy/decompress or one decode/clip/encode, not a whole-district pass.
pub fn composeTile(gpa: std.mem.Allocator, part: *const engine.geometry.partition.Partition, readers: []const *engine.pmtiles.Reader, z: u8, tx: u32, ty: u32, gzip: bool) !TileResult {
    const compose = engine.scene.compose;
    const map = part.mapForZoom(z) orelse return .{ .tile = null, .owned = false };
    const scale: f64 = @floatFromInt(@as(u64, 1) << @intCast(z));

    var arena = std.heap.ArenaAllocator.init(gpa);
    defer arena.deinit();
    const ta = arena.allocator();

    // Pass-1-equivalent for this one tile: walk owners in face order (the batch's tie order), cull
    // by face bbox, classify. The FIRST owner that fully owns the tile (buffer included) and has a
    // native blob wins the verbatim copy — faces are a disjoint partition, so that owner is unique.
    // Every other contributing owner (seam, or fully-owned-but-no-native) is collected in face order.
    // `owned` = at least one cell's coverage face covers this tile (the partition says it SHOULD
    // render here) — so a caller can tell a transient/erroneous empty from true empty ocean.
    var owned = false;
    var slots = std.ArrayList(u32).empty;
    for (map.faces, 0..) |face, slot| {
        if (face.owned.len == 0) continue;
        const ci = face.index;
        const cscl = part.cells[ci].cscl;
        const bb = faceTileBBox(face, scale);
        if (tx < bb.tx0 or tx > bb.tx1 or ty < bb.ty0 or ty > bb.ty1) continue;

        var grid = try engine.geometry.plane.EdgeGrid.init(ta, face.owned, tileWidthE7(z));
        defer grid.deinit();
        switch (grid.classify(tileClassifyBox(z, tx, ty))) {
            .full => continue, // owns none of this tile
            .empty => { // owns the whole tile: verbatim blob if present, else fall through
                owned = true;
                if (gzip) {
                    if (try readers[ci].getCompressed(z, tx, ty)) |blob| return .{ .tile = try gpa.dupe(u8, blob), .owned = true };
                } else if (try readers[ci].getTile(ta, z, tx, ty)) |raw| return .{ .tile = try gpa.dupe(u8, raw), .owned = true };
            },
            .seam => owned = true,
        }
        if (!(try ownerHasTile(readers[ci], cscl, z, tx, ty))) continue;
        const face_px = try compose.projectFace(ta, face.owned, z, tx, ty);
        if (face_px.len == 0) continue;
        try slots.append(ta, @intCast(slot));
    }
    if (slots.items.len == 0) return .{ .tile = null, .owned = owned };

    const enc = (try composeSeamTile(ta, part, map, readers, slots.items, z, tx, ty)) orelse return .{ .tile = null, .owned = owned };
    // gzip=true → match the archive's stored (gzipped) bytes; gzip=false → hand back the raw MLT.
    const bytes = if (gzip) try engine.pmtiles.StreamWriter.gzipTile(gpa, enc) else try gpa.dupe(u8, enc);
    return .{ .tile = bytes, .owned = true };
}

/// The outcome of composing one tile: its bytes (null if nothing rendered) and whether the ownership
/// partition says a cell SHOULD render here. `tile == null and owned` = expected-but-empty (a cell
/// owns the ground but produced nothing — transient during a bake, suspect once a bake is done);
/// `tile == null and !owned` = true empty (no cell owns this ground — open ocean, safe to cache).
pub const TileResult = struct { tile: ?[]u8, owned: bool };

/// A resident compositor: the per-cell archives held mmap'd and the ownership partition built once
/// (or loaded from a sidecar), so `serve` composes any tile without a whole-district pass. Open once,
/// serve many, deinit. Only coverage-carrying archives are kept; cell index == reader index. This is
/// the runtime backing for on-demand serving — the batch is for producing a full archive; this is for
/// a camera asking for tiles.
pub const ComposeSource = struct {
    gpa: std.mem.Allocator,
    arena: std.heap.ArenaAllocator, // owns the readers/maps arrays + adapted cells (borrowed by part)
    maps: []const []align(std.heap.page_size_min) const u8,
    readers: []const *engine.pmtiles.Reader,
    part: engine.geometry.partition.Partition,
    minz: u8,
    maxz: u8,
    loop_max: u8, // deepest zoom the sources can serve (native windows + one fill-up overscale zoom)
    bounds: [4]f64, // union coverage [west, south, east, north] in degrees

    /// Compose one tile → raw (decompressed) MLT + the ownership flag (gpa-owned bytes; null when
    /// nothing rendered — `owned` then says whether a cell SHOULD have). This is what a live tile
    /// server hands its HTTP layer, which gzips on the wire. Byte-faithful to the batch.
    pub fn serve(self: *ComposeSource, gpa: std.mem.Allocator, z: u8, tx: u32, ty: u32) !TileResult {
        return composeTile(gpa, &self.part, self.readers, z, tx, ty, false);
    }
    /// Serialize the resident ownership partition to a sidecar blob (gpa-owned) a later open can
    /// load to skip the owned-face build.
    pub fn serializePartition(self: *ComposeSource, gpa: std.mem.Allocator) ![]u8 {
        return engine.geometry.partition.serialize(gpa, &self.part);
    }
    pub fn deinit(self: *ComposeSource) void {
        const gpa = self.gpa;
        self.part.deinit();
        for (self.readers) |rp| rp.deinit();
        for (self.maps) |m| std.posix.munmap(m);
        self.arena.deinit();
        gpa.destroy(self);
    }
};

/// Open a resident ComposeSource over per-cell PMTiles at `paths` (mmap'd, so the cell set is never
/// fully resident). If `load_partition` is non-null and valid for this cell set the partition is
/// loaded (no build); else it is built. Returns null if no archive carries coverage. Free with
/// `ComposeSource.deinit`.
pub fn openComposeSourceFiles(io: std.Io, gpa: std.mem.Allocator, paths: []const []const u8, load_partition: ?[]const u8) !?*ComposeSource {
    const pmtiles = engine.pmtiles;
    const scene = engine.scene;
    const src = try gpa.create(ComposeSource);
    src.* = .{ .gpa = gpa, .arena = std.heap.ArenaAllocator.init(gpa), .maps = &.{}, .readers = &.{}, .part = undefined, .minz = 0, .maxz = 0, .loop_max = 0, .bounds = .{ 0, 0, 0, 0 } };
    errdefer {
        src.arena.deinit();
        gpa.destroy(src);
    }
    const a = src.arena.allocator();

    // mmap + open each archive; keep only those carrying coverage, so readers/maps/shims stay
    // aligned (cell index == reader index) for composeTile.
    var readers = std.ArrayList(*pmtiles.Reader).empty;
    var maps = std.ArrayList([]align(std.heap.page_size_min) const u8).empty;
    var shims = std.ArrayList(LoadedCov).empty;
    var built_part = false;
    errdefer {
        for (readers.items) |rp| rp.deinit();
        for (maps.items) |m| std.posix.munmap(m);
        if (built_part) src.part.deinit();
    }
    var minz: u8 = 255;
    var maxz: u8 = 0;
    var ubox = [4]f64{ 1e9, 1e9, -1e9, -1e9 }; // union coverage [w, s, e, n]
    for (paths) |path| {
        var f = std.Io.Dir.cwd().openFile(io, path, .{}) catch continue;
        const st = f.stat(io) catch {
            f.close(io);
            continue;
        };
        const len: usize = @intCast(st.size);
        if (len == 0) {
            f.close(io);
            continue;
        }
        const map = std.posix.mmap(null, len, .{ .READ = true }, .{ .TYPE = .PRIVATE }, f.handle, 0) catch {
            f.close(io);
            continue;
        };
        f.close(io);
        const rp = a.create(pmtiles.Reader) catch {
            std.posix.munmap(map);
            continue;
        };
        rp.* = pmtiles.Reader.init(gpa, map) catch {
            std.posix.munmap(map);
            continue;
        };
        const meta = readMetaJson(a, rp) orelse {
            rp.deinit();
            std.posix.munmap(map);
            continue;
        };
        const cc = (scene.coverage.decodeFromMetadata(a, meta) catch null) orelse {
            rp.deinit();
            std.posix.munmap(map);
            continue;
        };
        const bz = engine.bake_enc.bandZooms(engine.bake_enc.bandOf(cc.cscl));
        minz = @min(minz, bz.min);
        maxz = @max(maxz, bz.max);
        const b = [4]f64{
            @as(f64, @floatFromInt(cc.bbox[0])) / 1e7, @as(f64, @floatFromInt(cc.bbox[1])) / 1e7,
            @as(f64, @floatFromInt(cc.bbox[2])) / 1e7, @as(f64, @floatFromInt(cc.bbox[3])) / 1e7,
        };
        ubox[0] = @min(ubox[0], b[0]);
        ubox[1] = @min(ubox[1], b[1]);
        ubox[2] = @max(ubox[2], b[2]);
        ubox[3] = @max(ubox[3], b[3]);
        try maps.append(a, map);
        try readers.append(a, rp);
        try shims.append(a, .{ .name = cc.name, .date = cc.date, .cscl = cc.cscl, .coverage = cc.cov1, .bounds = b });
    }
    if (readers.items.len == 0) {
        src.arena.deinit();
        gpa.destroy(src);
        return null;
    }

    const cells = try toPlaneCells(a, shims.items);
    for (cells, readers.items) |*c, rp| c.reach = @max(bandReach(c.cscl), rp.header.max_zoom);

    var loaded = false;
    if (load_partition) |bytes| {
        if (engine.geometry.partition.deserialize(gpa, bytes, cells)) |p| {
            src.part = p;
            loaded = true;
        } else |err| std.debug.print("  partition sidecar unusable ({s}); building\n", .{@errorName(err)});
    }
    if (!loaded) src.part = try engine.geometry.partition.build(gpa, cells);
    built_part = true;

    const fill_max = @min(maxz + engine.bake_enc.FILLUP_DZ, engine.bake_enc.FILLUP_CEIL);
    src.maps = maps.items;
    src.readers = readers.items;
    src.minz = minz;
    src.maxz = maxz;
    src.loop_max = @max(maxz, fill_max);
    src.bounds = ubox;
    return src;
}

// The output-layer slot for a decoded layer name (one of scene.VECTOR_LAYERS), or null to drop.
fn layerIndex(name: []const u8) ?usize {
    for (engine.mvt.VECTOR_LAYERS, 0..) |ln, i| {
        if (std.mem.eql(u8, ln, name)) return i;
    }
    return null;
}

// Decode a per-cell tile by its stored type (.mlt for our bakes, .mvt otherwise).
fn decodeTile(a: std.mem.Allocator, tt: engine.pmtiles.TileType, raw: []const u8) ![]engine.mvt.DecodedLayer {
    return switch (tt) {
        .mlt => engine.mlt.decode(a, raw),
        else => engine.mvt.decode(a, raw),
    };
}

// The decoded layers cell `r` contributes at (z,tx,ty): its native tile if it has one, else —
// when z is within the fill-up window just past the cell's band native max — its deepest native
// ancestor tile with the features scaled up into this descendant (overscale). null = nothing
// reachable (below native, or a coarse-only zoom beyond the fill-up window, where the client
// camera + MapLibre overzoom take over). Everything is arena-allocated in `a`.
fn ownerTile(a: std.mem.Allocator, r: *engine.pmtiles.Reader, cscl: i32, z: u8, tx: u32, ty: u32) !?[]engine.mvt.DecodedLayer {
    const tt = r.header.tile_type;
    if (try r.getTile(a, z, tx, ty)) |raw| return try decodeTile(a, tt, raw);

    const nmax = engine.bake_enc.bandZooms(engine.bake_enc.bandOf(cscl)).max;
    if (z <= nmax or z > nmax + engine.bake_enc.FILLUP_DZ or z > engine.bake_enc.FILLUP_CEIL) return null;
    const shift: u5 = @intCast(z - nmax);
    const anc = (try r.getTile(a, nmax, tx >> shift, ty >> shift)) orelse return null;
    const layers = try decodeTile(a, tt, anc);
    scaleUpTile(layers, shift, tx, ty);
    return layers;
}

// The deepest zoom a cell's band ladder can serve — its native window max, or the fill-up
// overscale window just past it (`ownerTile`'s window, which FILLUP_CEIL can pull BELOW the
// native max for the finest bands — hence the @max). The band terms of `plane.Cell.reach`.
fn bandReach(cscl: i32) u8 {
    const nmax = engine.bake_enc.bandZooms(engine.bake_enc.bandOf(cscl)).max;
    return @max(nmax, @min(nmax + engine.bake_enc.FILLUP_DZ, engine.bake_enc.FILLUP_CEIL));
}

// Cheap existence mirror of `ownerTile` (directory probes only — no decompress, no decode):
// would it return content for cell `r` at (z,tx,ty)? Must stay in lockstep with it — the
// tile-major compositor's discovery pass uses this to reproduce the compose predicate, and
// the two passes must agree on which tiles compose.
fn ownerHasTile(r: *engine.pmtiles.Reader, cscl: i32, z: u8, tx: u32, ty: u32) !bool {
    if ((try r.getCompressed(z, tx, ty)) != null) return true;
    const nmax = engine.bake_enc.bandZooms(engine.bake_enc.bandOf(cscl)).max;
    if (z <= nmax or z > nmax + engine.bake_enc.FILLUP_DZ or z > engine.bake_enc.FILLUP_CEIL) return false;
    const shift: u5 = @intCast(z - nmax);
    return (try r.getCompressed(nmax, tx >> shift, ty >> shift)) != null;
}

// Scale an ancestor tile's features up into descendant (tx,ty) — the sub-cell `shift` levels
// finer: pixel (px,py) → (px<<shift − sx·EXTENT, py<<shift − sy·EXTENT), where (sx,sy) is the
// descendant's position in the ancestor's 2^shift grid. Out-of-sub-cell geometry lands outside
// the tile box and is dropped by the later clip-to-owned-face. In place; `shift` is bounded by
// FILLUP_DZ so the scaled coordinates stay within i32.
fn scaleUpTile(layers: []engine.mvt.DecodedLayer, shift: u5, tx: u32, ty: u32) void {
    const E: i64 = engine.tile.EXTENT;
    const scale: i64 = @as(i64, 1) << @as(u6, shift);
    const mask: u32 = (@as(u32, 1) << shift) - 1;
    const sx: i64 = @intCast(tx & mask);
    const sy: i64 = @intCast(ty & mask);
    for (layers) |layer| for (layer.features) |feat| for (feat.parts) |part| for (part) |*p| {
        p.x = @intCast(@as(i64, p.x) * scale - sx * E);
        p.y = @intCast(@as(i64, p.y) * scale - sy * E);
    };
}

// Re-orient each polygon feature's rings (the sole MVT winding authority). Non-area features
// pass through; the input `properties` are borrowed unchanged (draw_prio et al. survive).
fn orientPolys(a: std.mem.Allocator, feats: []const engine.mvt.Feature) ![]const engine.mvt.Feature {
    const mvt = engine.mvt;
    const out = try a.alloc(mvt.Feature, feats.len);
    for (feats, 0..) |f, i| {
        out[i] = if (f.geom_type == .polygon)
            .{ .id = f.id, .geom_type = .polygon, .parts = try engine.mvt.orientAreaRings(a, f.parts), .properties = f.properties }
        else
            f;
    }
    return out;
}

// The metadata JSON of an archive (decompressed), borrowed from the reader (or `a` if gzipped),
// or null if absent/unreadable.
fn readMetaJson(a: std.mem.Allocator, r: *engine.pmtiles.Reader) ?[]const u8 {
    const h = r.header;
    if (h.metadata_length == 0) return null;
    const raw = r.bytes[@intCast(h.metadata_offset)..][0..@intCast(h.metadata_length)];
    return switch (h.internal_compression) {
        .none => raw,
        .gzip => engine.gzip.decompress(a, raw) catch return null,
        else => null,
    };
}

// The "scamin" ladder from an archive's metadata JSON, or empty if absent/unparseable.
fn parseScamin(a: std.mem.Allocator, meta: []const u8) []const u32 {
    const Dto = struct { scamin: []const u32 = &.{} };
    const v = std.json.parseFromSliceLeaky(Dto, a, meta, .{ .ignore_unknown_fields = true }) catch return &.{};
    return v.scamin;
}
